[EMAIL]
ADDRESS = "benithafrancy3@gmail.com"
PASSWORD = "pfop xyyp mjeh iqaa"

[GCREDS]
GCREDS_JSON = """
{
   "type": "service_account",
  "project_id": "resumerecruitmentbot",
  "private_key_id": "49c734e38996669b195e096a572fe76fa5d61b83",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCr7JenddwEwKXs\nygMxajpvgBbiz7pU+noOtus4lHL5bo/8qWvuNyyHK3SqVc3QZHwt9Awm91Y8lf0D\nCDCU+qMDI8vlju+4iaATYiYtKWGG69ORIzNmBnN71m4a8BcW6kxmn0rQ3Eowqt3j\neQTe6s8xlMH9fd6v+XCZyPZUSm1hFVOsfx2/MyOir7uq7IhEGKBmsirZVrqTDirM\nJvMRcMcKjrzxzHWlyZjvedpjfxtgb74NqaLZ7sqnG779ZU0NMi+hUTWbW7S1QbH6\nT90zl2Xl4Av9oGaXqpDETBituSnXX+tul8Nd2PPzONLgu7SHyr1Le6KavkBG3r1Q\nZ32DXf6PAgMBAAECggEATDURfB9YKZsjcXSSOcM2p9oFSwB9PdHRbNhUJ75VwI7r\nsDmBKBS43im7Cw4Brw/7o3r8MAGO7kgl4MQulLsMqwWhCd50ED6hADaPaZFgM6gx\nHbKWw/C0G/6Oy84EzhmJSCvvw+kB0dTLiltId29p7DZeTvkOTr6o1OIpnm9nUJKh\nzblHujCDMVdfN4Byuap482/F9ppkmwTH3rEBNlXnoSVHMApT2ICax0+vCEVvsp6V\nkGaB8Pe/jsejoxi0T4dtKfU/0Ze2cJ+ku4WNglRGaNz4w0OtCQ+ZGWw3cpYFPvIk\n6Xt+jIUlw3WZJOgiYqGlZ1Kt7uoGTr5cl9AVnxMb0QKBgQDwdN8oGJxtzRYZc8Qi\n2Dk8Wr/a3Fy+yvQg+J+3l+8RftbWHqkmm32dWNNLGTtrxb/rgEgAtdffFz9WI3+D\nzbREfDnwptcbaPZkLX3ss98qLYeRkzeoH6p6wVwXvnByv77IOFA1SonDChfx8jfC\nAYPRslMzClA9c5srLucItmgdgwKBgQC3CaHZqtEJQPcg0v/E4E8b37y4hHkDJ2wF\nY7V7CRF+EkIKsnvEv7Rqe/90w+OPhtI5dGgLt9K+LGlQ6QRDvPuPPK/U2qYe8Z0o\nuZJAhDdEJv/dM1PtL4EHCf5TLrhnqqAiWglf3PUJrCuARd7GLH8AhymNfqEKqVin\n6d86zgv5BQKBgQDAdVrT9fbmr5r7njwjg5s0IpKi83PMRhdmeHkl8paoEzSTRxEu\nVJATK7Ba0IRN+4ZkUVXQM7vn1Oyd3mXGshOSKTga1P8g8j8b6Yl7tnBtiumSbBnF\nGCtUe4Vhf8zzG2PxT5lrPhDLqj2GKs/UGXBPnAKZvKyCsxBEXRMQVyc4TwKBgQCE\nSE3UhgM08OKpslRu8L27o2M852CdyuviqUELfm5J8uAP4xZYB0RYgO0KclgP7pwY\nMezQKzX/gxFKDF2spvQXfQCGkM7mJjAysorkXamjc5wPPX02OdLCR5Kqg2V6ZnH8\n4Z1Mzt+48dkuh1CNYLMYqpZ5UD8K+YC9OeS/FxLIEQKBgBM8YPG1v3MHVQEGR5ef\nQfpdsZway2dhEEzSxn7VYcOYbAkrd/T4eOhbBKr266ogrbdigwneET4b46L3AFnF\nwJH6UCh0ZmJt8DPjeH9843IFussXUICobX9MW0VsDdsTfPRh8e8eoEzmLoowWRjV\negIN2o+njMtwuVtuD2HUg0dZ\n-----END PRIVATE KEY-----\n",
  "client_email": "resumebot@resumerecruitmentbot.iam.gserviceaccount.com",
  "client_id": "117372201678442694554",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/resumebot%40resumerecruitmentbot.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
